[package]
name = "maelstrom"
version = "0.1.0"
authors = ["Chris Bruce <chris@chrisbruce.com>", "Aiden McClelland <me@drbonez.dev>"]
edition = "2018"


[dependencies]
actix-cors = "0.2.0"
actix-rt = "1.0"
actix-web = "2.0"
async-trait = "0.1.30"
dotenv = "0.15"
log = "0.4"
env_logger = "0.7"
jsonwebtoken = "7.1.0"
lazy_static = "1.4.0"
serde = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
sqlx = { version = "0.3", default-features = false, features = [ "runtime-tokio", "macros", "postgres", "sqlite" ] }
ruma-identifiers = "0.14"
structopt = "0.3"
url = { version = "2.1", features = [ "serde" ] }
anyhow = "1.0"